name: CI/CD Java + Docker

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Dar permissão ao mvnw
        run: chmod +x ./mvnw
        working-directory: demo

      - name: Rodar testes
        run: ./mvnw test
        working-directory: demo

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Dar permissão ao mvnw
        run: chmod +x ./mvnw
        working-directory: demo

      - name: Build .jar (sem testes)
        run: ./mvnw clean package -DskipTests
        working-directory: demo

      - name: Upload artefato .jar
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: demo/target/*.jar

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artefato .jar
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: demo/target/

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}-${{ github.sha }}
          name: Release ${{ github.run_number }}-${{ github.sha }}
          draft: false
          prerelease: false
          files: demo/target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build imagem Docker
        run: docker build -t nessa742/test-ci-cd:${{ github.sha }} .
      
      - name: Push imagem Docker
        run: docker push nessa742/test-ci-cd:${{ github.sha }}
